name: summary
on: workflow_dispatch

jobs:
  summary:
    name: Summary
    runs-on: ubuntu-latest

    steps:
      - name: Create Release
        run: |
          echo "### Artifacts List" >> $GITHUB_STEP_SUMMARY
          echo "| -------- | ------------ |" >> $GITHUB_STEP_SUMMARY
          echo "| Project1 | Docker Image |" >> $GITHUB_STEP_SUMMARY
          echo "| Project2 | Docker Image |" >> $GITHUB_STEP_SUMMARY
          echo "| Library1 | Jar File |" >> $GITHUB_STEP_SUMMARY
          echo "| Project3 | Docker Image |" >> $GITHUB_STEP_SUMMARY
          echo "| Library2 | Jar File |" >> $GITHUB_STEP_SUMMARY
